sudo: required

language: bash
services: docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - sudo curl -L https://raw.githubusercontent.com/metowolf/docker-builder/master/scripts/publish.sh -o /usr/local/bin/docker-publish
  - sudo chmod +x /usr/local/bin/docker-publish

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t travis .
      if [ "$TRAVIS_TAG" != "" ]; then
        image_version=`echo -e "$TRAVIS_TAG\c" | awk -F 'v' '{print $2}'`
      else
        image_version=$(cat index.php | grep 'const VERSION = ' | awk -F "'" '{print $2}')-dev
      fi
      docker-publish travis idawnlight/avatar-cache:${image_version}
    )
after_script:
  - docker images