name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Write Commit Hash
        run: echo ${{ github.sha }} >> commit_hash
      - uses: jerray/publish-docker-action@master
        with:
          username: idawnlight
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: idawnlight/avatar-cache
          auto_tag: true
